// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyDBContext;

namespace MyDB.Migrations
{
    [DbContext(typeof(MyDBContext.MyDBContext))]
    partial class MyDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DomainDTO.EFTables.SysOUMembersEFTables", b =>
                {
                    b.Property<int>("OUMemberId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("LeaderTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OUID")
                        .HasColumnType("int");

                    b.Property<int>("UId")
                        .HasColumnType("int");

                    b.Property<string>("UserAccount")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OUMemberId");

                    b.ToTable("SysOUMembersEFTables");
                });

            modelBuilder.Entity("DomainDTO.EFTables.SysOURoleMembersEFTables", b =>
                {
                    b.Property<int>("OURoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OUID")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserAccount")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OURoleId");

                    b.ToTable("SysOURoleMembersEFTables");
                });

            modelBuilder.Entity("DomainDTO.EFTables.SysOURolesEFTables", b =>
                {
                    b.Property<int>("OUROleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("OUID")
                        .HasColumnType("int");

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("OUROleID");

                    b.ToTable("SysOURolesEFTables");
                });

            modelBuilder.Entity("DomainDTO.EFTables.SysOUsEFTables", b =>
                {
                    b.Property<int>("OUID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OULevel")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OUName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("int");

                    b.Property<int>("ParentOUID")
                        .HasColumnType("int");

                    b.HasKey("OUID");

                    b.ToTable("SysOUsEFTables");
                });

            modelBuilder.Entity("DomainDTO.EFTables.SysUsersEFTables", b =>
                {
                    b.Property<int>("UId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Account")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Disabled")
                        .HasColumnType("bit");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Img")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sex")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SysUser")
                        .HasColumnType("int");

                    b.HasKey("UId");

                    b.ToTable("SysUsersEFTables");
                });
#pragma warning restore 612, 618
        }
    }
}
